name: flutter_application_2
description: Animal Corner is a mobile application designed to streamline pet profiling and appointment scheduling, addressing the operational needs of pet clinics while enhancing convenience for pet owners. The app allows users to create and manage pet profiles, schedule veterinary appointments, and facilitate seamless communication between pet owners and clinics.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.0
  shared_preferences: ^2.2.2
  flutter_datetime_picker: ^1.5.1
  table_calendar: ^3.2.0
  provider: ^6.1.4
  flutter_staggered_animations: ^1.1.0
  url_launcher: ^6.2.4
  firebase_app_check: ^0.3.1+6
  js: ^0.7.1
  gradle_properties: ^1.0.2
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.1.5
  timezone: ^0.10.0

  fluttertoast: ^8.2.8


flutter:
  uses-material-design: true
  assets:
    - assets/cat.png
    - assets/dog.png
    - assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  adaptive_icon_background: "#000000" # Or any solid color you prefer
  adaptive_icon_foreground: "assets/logo.png"



